# Site settings
title: The Startled Badger
email: 
description: A blog about stuff this startled badger has found itself doing
baseurl: ""
url: "http://thestartledbadger.github.io"
github_username:  TheStartledBadger


#
theme: jekyll-theme-hacker

# At some point jekyll will upgrade and
# gems := plugins
# but right now if I put in "plugins" I get told to use "plugins_dir"
# which is an error relating to a completely different setting!
gems:
  - jekyll-seo-tag
